/* SentriX guidance pages for the unified dashboard. */
async function guidanceDiagnostic(force=false){
  return cached('guidance-v56',()=>gget('/diagnostic-v1'),{force,ttl:30000});
}
function guidanceOverviewBlock(d){
  const steps=Array.isArray(d.onboarding)?d.onboarding:[];
  const done=steps.filter(x=>x.ready).length, issues=(d.issues||[]).length, score=Number(d.score||0);
  return '<section class="guidance-hero full"><div class="guidance-hero-main"><div><span class="guidance-kicker">Assistant SentriX</span><h2>État du serveur : '+score+'%</h2><p>'+(issues?plural(issues,'point')+' à vérifier.':'Aucun problème important détecté.')+'</p></div><div class="guidance-score '+(Number(d.summary?.bad||0)?'bad':issues?'warn':'ok')+'"><strong>'+score+'%</strong><span>Santé</span></div></div><div class="guidance-quick"><button class="guidance-action" data-guidance-page="diagnostic" type="button"><b>Diagnostic complet</b><span>Permissions, rôles, logs, tickets et IA</span></button><button class="guidance-action" data-guidance-page="onboarding" type="button"><b>Démarrage guidé · '+done+'/4</b><span>Sécurité → Logs → Tickets → Bienvenue</span></button><button class="guidance-action" data-guidance-page="feedback" type="button"><b>Bug / Avis</b><span>Signaler un problème ou proposer une amélioration</span></button></div></section>';
}
function bindGuidanceOverview(root=content()){
  root.querySelectorAll('[data-guidance-page]').forEach(b=>b.onclick=()=>go(b.dataset.guidancePage));
}
async function renderGuidanceDiagnostic(){
  const d=await guidanceDiagnostic(true),systems=d.systems||[],issues=d.issues||[];
  content().innerHTML='<div class="grid"><section class="guidance-diagnostic-head full"><div><span class="guidance-kicker">Centre de diagnostic</span><h2>'+esc(d.guild?.name||'Serveur')+'</h2><p>Permissions, hiérarchie, logs, tickets, IA et réglages essentiels.</p></div><div class="guidance-score '+(Number(d.summary?.bad||0)?'bad':Number(d.summary?.warn||0)?'warn':'ok')+'"><strong>'+Number(d.score||0)+'%</strong><span>Santé</span></div></section><section class="card full"><div class="kpis">'+kpi('Systèmes OK',number(d.summary?.ok))+kpi('Attention',number(d.summary?.warn))+kpi('Bloquants',number(d.summary?.bad))+kpi('Latence',d.latency_ms!=null?d.latency_ms+' ms':'—')+'</div></section><section class="card full"><div class="card-head"><div><h2>État des systèmes</h2><p>Ce que SentriX peut réellement utiliser maintenant.</p></div></div><div class="guidance-system-list">'+systems.map(x=>'<div class="guidance-system"><div><b>'+esc(x.name)+'</b><span>'+esc(x.detail)+'</span></div><span class="badge '+(x.status==='ok'?'ok':x.status==='bad'?'bad':'warn')+'">'+(x.status==='ok'?'OK':x.status==='bad'?'Erreur':'Attention')+'</span></div>').join('')+'</div></section><section class="card full"><div class="card-head"><div><h2>À corriger</h2><p>SentriX vous envoie directement vers le bon réglage.</p></div><span class="badge '+(issues.length?'warn':'ok')+'">'+number(issues.length)+'</span></div><div class="guidance-issue-list">'+(issues.length?issues.map(x=>'<div class="guidance-issue"><div><b>'+esc(x.title)+'</b><span>'+esc(x.detail)+'</span></div>'+(x.tab?'<button class="btn sm" type="button" data-guidance-tab="'+esc(x.tab)+'">Configurer</button>':'')+'</div>').join(''):emptyState('Aucun problème important détecté','Les contrôles principaux sont au vert.'))+'</div></section></div>';
  content().querySelectorAll('[data-guidance-tab]').forEach(b=>b.onclick=()=>go(b.dataset.guidanceTab));
}
async function renderGuidanceOnboarding(){
  const d=await guidanceDiagnostic(true),steps=d.onboarding||[],done=steps.filter(x=>x.ready).length;
  const rows=steps.map((x,i)=>'<article class="guidance-step '+(x.ready?'done':'')+'"><span class="guidance-step-num">'+(i+1)+'</span><div><h3>'+esc(x.title)+(x.ready?' · Terminé':'')+'</h3><p>'+esc(x.detail)+'</p></div><button class="btn sm '+(x.ready?'':'primary')+'" type="button" data-onboarding-step="'+esc(x.key)+'">'+(x.ready?'Vérifier':'Configurer')+'</button></article>').join('');
  content().innerHTML='<div class="grid"><section class="guidance-diagnostic-head full"><div><span class="guidance-kicker">Nouveau serveur</span><h2>Configuration guidée</h2><p>Quatre étapes : Sécurité, Logs, Tickets, Bienvenue.</p></div><div class="guidance-score '+(done===steps.length?'ok':'warn')+'"><strong>'+done+'/'+(steps.length||4)+'</strong><span>Étapes</span></div></section><section class="card full"><div class="guidance-progress"><i style="width:'+(steps.length?Math.round(done/steps.length*100):0)+'%"></i></div><div class="guidance-step-list">'+rows+'</div></section></div>';
  const map={security:'security',logs:'logs',tickets:'tickets',welcome:'welcome'};
  content().querySelectorAll('[data-onboarding-step]').forEach(b=>b.onclick=()=>go(map[b.dataset.onboardingStep]||'overview'));
}
async function renderGuidanceFeedback(){
  content().innerHTML='<div class="grid"><section class="guidance-diagnostic-head full"><div><span class="guidance-kicker">Retour utilisateur</span><h2>Bug / Avis</h2><p>Dites ce qui ne va pas ou ce que vous aimeriez améliorer.</p></div></section><section class="card full"><div class="fields"><div class="field"><label>Type</label><select id="guideKind"><option value="bug">Bug</option><option value="opinion">Avis</option></select></div><div class="field"><label>Note</label><select id="guideRating"><option value="">Sans note</option><option value="5">5 / 5</option><option value="4">4 / 5</option><option value="3">3 / 5</option><option value="2">2 / 5</option><option value="1">1 / 5</option></select></div><div class="field full"><label>Message</label><textarea id="guideMessage" maxlength="1800" rows="7"></textarea></div></div><div class="notice">Seul le contexte technique minimal du dashboard est associé au retour.</div><div class="toolbar"><button class="btn primary" id="guideSend" type="button">Envoyer</button></div></section></div>';
  $('guideSend').onclick=async()=>{const message=$('guideMessage').value.trim();if(message.length<8)return toast('Ajoutez un peu plus de détails.',true);const b=$('guideSend');b.disabled=true;try{const r=await gpost('/feedback-v1',{kind:$('guideKind').value,rating:$('guideRating').value||null,message,page:'/app',technical:{tab:'feedback',viewport:String(innerWidth)+'x'+String(innerHeight),error:''}});$('guideMessage').value='';toast(r.message||'Retour enregistré.')}catch(e){toast(e.message,true)}finally{b.disabled=false}};
}
