"""SentriX dashboard adapter for the real unified V2 production DOM.

V4/V5/V6 were originally written against the pre-V55 DOM (``#serverContent`` / ``#fields``).
Production V55 serves ``dashboard_unified_v2`` instead, whose stable anchors are ``.workspace``
and ``#content``.  This layer is intentionally presentation-first and reuses the existing
backend/routes; the verification publish action explicitly saves the unified V2 selections,
then calls the real V96 dashboard route.
"""
from __future__ import annotations

import logging

logger = logging.getLogger("bot.dashboard-unified-adapter-v9")

V9_CSS = r'''
<style id="sentrix-unified-adapter-v9-css">
body[data-sx-dashboard-v9="1"]{--sxv9-accent:#4da3ff;--sxv9-soft:#13283d;--sxv9-line:#29445f;background:radial-gradient(circle at 72% -10%,#102a40 0,#0a111a 34%,#070c12 78%)!important}
body[data-sx-dashboard-v9="1"] .workspace{max-width:none!important;padding-top:22px!important;background:transparent!important}
body[data-sx-dashboard-v9="1"] .workspace-head{padding:0 0 16px!important;border-bottom:1px solid #1b2b3b!important}
#sxUnifiedHeroV9{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:18px;align-items:center;margin:0 0 16px;padding:18px 20px;border:1px solid var(--sxv9-line);border-radius:15px;background:linear-gradient(135deg,#102032,#0c1723 60%,#0b141e);box-shadow:0 18px 42px #0004;overflow:hidden;position:relative}
#sxUnifiedHeroV9:after{content:"";position:absolute;width:220px;height:220px;border-radius:50%;right:-95px;top:-120px;background:var(--sxv9-accent);opacity:.09;pointer-events:none}
.sxv9-hero-main{display:flex;align-items:center;gap:14px;min-width:0}.sxv9-icon{width:48px;height:48px;border-radius:13px;display:grid;place-items:center;flex:0 0 auto;border:1px solid color-mix(in srgb,var(--sxv9-accent) 55%,#20364a);background:color-mix(in srgb,var(--sxv9-accent) 16%,#0d1823);color:var(--sxv9-accent);font-size:15px;font-weight:950}.sxv9-copy{min-width:0}.sxv9-kicker{font-size:9px;letter-spacing:.13em;text-transform:uppercase;color:var(--sxv9-accent);font-weight:950}.sxv9-copy h2{margin:2px 0 3px;font-size:24px;letter-spacing:-.035em}.sxv9-copy p{margin:0;color:#8fa1b5;font-size:11px;max-width:760px}.sxv9-actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end;z-index:1}.sxv9-live{display:inline-flex;align-items:center;gap:7px;padding:8px 10px;border-radius:9px;border:1px solid #285541;background:#10251c;color:#75e5ad;font-size:10px;font-weight:900}.sxv9-live:before{content:"";width:7px;height:7px;border-radius:50%;background:#55d69a;box-shadow:0 0 10px #55d69a88}

body[data-sx-dashboard-v9="1"] #content .card{border-color:#20364a!important;background:linear-gradient(180deg,#0e1924,#0b141d)!important;box-shadow:0 10px 28px #0002!important;border-radius:13px!important}
body[data-sx-dashboard-v9="1"] #content .field input,body[data-sx-dashboard-v9="1"] #content .field select,body[data-sx-dashboard-v9="1"] #content .field textarea{background:#09131d!important;border-color:#29425a!important}
body[data-sx-tab="logs"]{--sxv9-accent:#55b7ff;--sxv9-soft:#11293c;--sxv9-line:#2b5878}body[data-sx-tab="logs"] #content .card{border-left:3px solid #429ee4!important}body[data-sx-tab="logs"] #content .fields{grid-template-columns:repeat(2,minmax(0,1fr))!important}
body[data-sx-tab="security"]{--sxv9-accent:#ff6978;--sxv9-soft:#351820;--sxv9-line:#63313d}body[data-sx-tab="security"] #content .card{border-top:2px solid #7d3443!important}
body[data-sx-tab="moderation"]{--sxv9-accent:#ff7a72;--sxv9-soft:#321a19;--sxv9-line:#653b37}body[data-sx-tab="moderation"] #content .row{border-left:2px solid #7a413d!important}
body[data-sx-tab="tickets"]{--sxv9-accent:#55dda5;--sxv9-soft:#122a21;--sxv9-line:#285844}body[data-sx-tab="tickets"] #content .card{border-radius:17px!important}
body[data-sx-tab="ai"]{--sxv9-accent:#a77bff;--sxv9-soft:#261d3d;--sxv9-line:#503d7c}body[data-sx-tab="ai"] #content .card{background:linear-gradient(160deg,#17172a,#0e1520)!important}
body[data-sx-tab="notifications"]{--sxv9-accent:#f1c85b;--sxv9-soft:#322a14;--sxv9-line:#62532a}body[data-sx-tab="notifications"] #content .card{border-top:2px solid #7b652d!important}
body[data-sx-tab="verification"]{--sxv9-accent:#50d5ff;--sxv9-soft:#102c38;--sxv9-line:#28617a}body[data-sx-tab="verification"] #content>.grid{grid-template-columns:1fr!important}
body[data-sx-tab="roles"]{--sxv9-accent:#91a8c4;--sxv9-soft:#1a2430;--sxv9-line:#384b61}body[data-sx-tab="roles"] #content .fields{grid-template-columns:repeat(3,minmax(0,1fr))!important}
body[data-sx-tab="economy"]{--sxv9-accent:#65df9b;--sxv9-soft:#132a1d;--sxv9-line:#2b5b40}
body[data-sx-tab="levels"]{--sxv9-accent:#70dda2;--sxv9-soft:#142d20;--sxv9-line:#2e6246}body[data-sx-tab="levels"] #content .metric strong{font-size:30px!important}
body[data-sx-tab="diagnostic"]{--sxv9-accent:#8f86ff;--sxv9-soft:#22203f;--sxv9-line:#494579}body[data-sx-tab="diagnostic"] #content .permission-grid{gap:10px!important}
body[data-sx-tab="welcome"]{--sxv9-accent:#62a9ff;--sxv9-soft:#152942;--sxv9-line:#315778}body[data-sx-tab="embeds"]{--sxv9-accent:#d08cff;--sxv9-soft:#2a1b35;--sxv9-line:#593a6f}body[data-sx-tab="config"]{--sxv9-accent:#79a9d7}body[data-sx-tab="access"]{--sxv9-accent:#72c7d5}
.sx-v9-hidden-legacy-verify{display:none!important}
#sxVerifyV9{grid-column:1/-1;border:1px solid #28708d;border-radius:16px;background:linear-gradient(145deg,#0e2531,#0a1822 60%,#0b141d);padding:18px;box-shadow:0 18px 42px #0004;position:relative;overflow:hidden}#sxVerifyV9:before{content:"";position:absolute;inset:0 auto 0 0;width:3px;background:#50d5ff}.sxv9-verify-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:14px}.sxv9-verify-head h3{margin:0;font-size:20px;letter-spacing:-.025em}.sxv9-verify-head p{margin:4px 0 0;color:#8faabc;font-size:11px;max-width:760px}.sxv9-captcha-badge{padding:7px 10px;border:1px solid #246a55;border-radius:999px;background:#102a22;color:#70e2b0;font-size:9px;font-weight:950;white-space:nowrap}.sxv9-verify-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.sxv9-vfield{min-width:0}.sxv9-vfield.full{grid-column:1/-1}.sxv9-vfield label{display:block;margin:0 0 5px;color:#d8eaf5;font-size:10px;font-weight:900}.sxv9-vfield input,.sxv9-vfield select,.sxv9-vfield textarea{width:100%;border:1px solid #31576d;border-radius:9px;background:#08141d;color:#eef8ff;padding:9px 10px}.sxv9-vfield textarea{min-height:120px;resize:vertical}.sxv9-verify-options{display:flex;align-items:center;gap:16px;flex-wrap:wrap;margin-top:12px;color:#b9cedb;font-size:10px}.sxv9-verify-options label{display:flex;align-items:center;gap:7px}.sxv9-verify-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-top:13px}.sxv9-verify-status{flex:1;min-width:240px;border:1px solid #29465a;border-radius:9px;background:#091822;color:#8fa8b9;padding:9px 11px;font-size:10px}.sxv9-verify-status.ok{border-color:#2d624b;color:#7fe2b1;background:#0f241c}.sxv9-verify-status.bad{border-color:#693642;color:#ff9fac;background:#251218}
@media(max-width:980px){#sxUnifiedHeroV9{grid-template-columns:1fr}.sxv9-actions{justify-content:flex-start}body[data-sx-tab="roles"] #content .fields{grid-template-columns:repeat(2,minmax(0,1fr))!important}}
@media(max-width:620px){.sxv9-verify-grid{grid-template-columns:1fr}.sxv9-vfield.full{grid-column:auto}.sxv9-verify-head{flex-direction:column}body[data-sx-tab="logs"] #content .fields,body[data-sx-tab="roles"] #content .fields{grid-template-columns:1fr!important}}
</style>
'''

V9_JS = r'''
<script id="sentrix-unified-adapter-v9-js">
(()=>{"use strict";if(window.__sentrixUnifiedAdapterV9)return;window.__sentrixUnifiedAdapterV9=true;
const $=id=>document.getElementById(id),S=()=>{try{return state}catch(_){return null}},fmt=n=>Number(n||0).toLocaleString("fr-FR");
const META={overview:["OV","Vue d’ensemble","Santé, activité et raccourcis essentiels du serveur."],welcome:["AD","Arrivées & départs","Parcours d’arrivée, départs et automatisations d’accueil."],levels:["NV","Progression","XP, niveaux et annonces de progression."],security:["SE","Protection active","AutoMod, anti-raid et permissions critiques."],moderation:["MO","Modération","Historique disciplinaire et actions administratives."],logs:["LG","Journalisation détaillée","Destinations, catégories et suivi des événements Discord."],verification:["VE","Vérification Discord","Règlement, CAPTCHA réel et attribution du rôle membre."],roles:["RO","Architecture des rôles","Rôles automatiques, staff et permissions utilisées par SentriX."],economy:["EC","Économie","Comptes persistants et accès aux fonctions économiques."],notifications:["NO","Diffusion sociale","Sources et destinations YouTube, TikTok, Twitch et autres."],tickets:["TI","Support structuré","Panels, types, publication et suivi des tickets."],ai:["AI","Moteur IA","Modèle, mémoire, limites et journalisation."],embeds:["EM","Embeds & design","Création et aperçu des messages Discord."],config:["CF","Configuration","Fondations et paramètres principaux du serveur."],access:["AC","Accès & commandes","Portée, commandes et gestionnaires SentriX."],diagnostic:["DG","Santé & diagnostic","Permissions, ressources cassées et état réel du serveur."]};
function info(){const t=S()?.tab||"overview";return META[t]||["SX","SentriX","Configuration du serveur."]}
function ensureHero(){const s=S(),ws=document.querySelector(".workspace"),head=ws?.querySelector(".workspace-head");if(!s?.guildData||!ws||!head)return;if(s.tab==="overview"){$("sxUnifiedHeroV9")?.remove();return}let hero=$("sxUnifiedHeroV9");if(!hero){hero=document.createElement("section");hero.id="sxUnifiedHeroV9";head.insertAdjacentElement("afterend",hero)}$("sxUnifiedKpisV9")?.remove();const i=info(),sig=[s.tab,s.guildId].join("|");if(hero.dataset.sig===sig)return;hero.dataset.sig=sig;hero.innerHTML=`<div class="sxv9-hero-main"><div class="sxv9-icon">${i[0]}</div><div class="sxv9-copy"><div class="sxv9-kicker">SentriX Control Center · V9</div><h2>${i[1]}</h2><p>${i[2]}</p></div></div><div class="sxv9-actions"><span class="sxv9-live">Temps réel</span><button class="btn" type="button" id="sxV9Refresh">Actualiser</button><button class="btn" type="button" id="sxV9Diagnostic">Diagnostic</button></div>`;$("sxV9Refresh")?.addEventListener("click",()=>{try{if(typeof refreshAll==="function")refreshAll()}catch(_){location.reload()}});$("sxV9Diagnostic")?.addEventListener("click",()=>{try{if(typeof go==="function")go("diagnostic")}catch(_){}})}
async function req(path,opt={}){const s=S(),headers={...(opt.headers||{})};if(opt.method&&opt.method!=="GET")headers["X-CSRF-Token"]=String(s?.csrf||"");if(opt.body)headers["Content-Type"]="application/json";const r=await fetch(path,{credentials:"same-origin",cache:"no-store",...opt,headers});let d={};try{d=await r.json()}catch(_){}if(!r.ok)throw new Error(d.error||`Erreur HTTP ${r.status}`);return d}
function copyOptions(from,to){if(!from||!to)return;to.innerHTML=from.innerHTML;to.value=from.value}
async function loadVerifyState(){const s=S(),box=$("sxV9VerifyStatus");if(!s?.guildId||!box)return;try{const d=await req(`/api/guilds/${encodeURIComponent(s.guildId)}/verification-v6`);box.className="sxv9-verify-status "+(d.published?"ok":"");box.textContent=d.published?`Panneau actif sur Discord${d.channel_name?` · #${d.channel_name}`:""}${d.role_name?` · @${d.role_name}`:""}`:"Prêt à configurer puis publier sur Discord.";if(!$("sxV9Title")?.dataset.touched)$("sxV9Title").value=d.title||"Règlement & vérification";if(!$("sxV9Rules")?.dataset.touched)$("sxV9Rules").value=d.rules_text||$("verifyRules")?.value||"";if(!$("sxV9Image")?.dataset.touched)$("sxV9Image").value=d.image_url||$("verifyImage")?.value||"";if(!$("sxV9Auto")?.dataset.touched)$("sxV9Auto").checked=!!d.auto_access;const b=$("sxV9Publish");if(b)b.textContent=d.published?"Mettre à jour sur Discord":"Publier sur Discord"}catch(e){box.className="sxv9-verify-status bad";box.textContent=e.message}}
async function publishVerify(){const s=S(),btn=$("sxV9Publish"),box=$("sxV9VerifyStatus");if(!s?.guildId||!btn)return;const channel=$("sxV9Channel")?.value||"",role=$("sxV9Role")?.value||"",rules=$("sxV9Rules")?.value||"",image=$("sxV9Image")?.value||"",captcha=!!$("sxV9Captcha")?.checked,tries=Number($("sxV9Tries")?.value||3);if(!channel||!role){box.className="sxv9-verify-status bad";box.textContent="Choisis le salon et le rôle avant de publier.";return}btn.disabled=true;box.className="sxv9-verify-status";box.textContent="Enregistrement puis publication Discord…";try{if(typeof v62Action!=="function")throw new Error("Le moteur de configuration unifié n’est pas chargé.");await v62Action({action:"verification_save",channel_id:channel,role_id:role,rules_text:rules,image_url:image,captcha_enabled:captcha,captcha_max_attempts:tries,publish:false});const d=await req(`/api/guilds/${encodeURIComponent(s.guildId)}/verification-v6/publish`,{method:"POST",body:JSON.stringify({title:$("sxV9Title")?.value||"Règlement & vérification",rules_text:rules,image_url:image,auto_access:!!$("sxV9Auto")?.checked})});box.className="sxv9-verify-status ok";box.textContent=d.message||"Panneau de vérification publié sur Discord avec CAPTCHA.";try{if(typeof toast==="function")toast(box.textContent)}catch(_){}await loadVerifyState()}catch(e){box.className="sxv9-verify-status bad";box.textContent=e.message;try{if(typeof toast==="function")toast(e.message,true)}catch(_){}}finally{btn.disabled=false}}
function mountVerification(){if(S()?.tab!=="verification")return;const content=$("content"),grid=content?.querySelector(":scope > .grid")||content;if(!grid||$("sxVerifyV9"))return;const oldChannel=$("verifyChannel"),oldRole=$("verifyRole"),oldRules=$("verifyRules"),oldImage=$("verifyImage"),oldCaptcha=$("verifyCaptcha"),oldTries=$("verifyTries");oldChannel?.closest(".card")?.classList.add("sx-v9-hidden-legacy-verify");const card=document.createElement("section");card.id="sxVerifyV9";card.innerHTML=`<div class="sxv9-verify-head"><div><h3>Vérification Discord réelle</h3><p>Publie le règlement dans Discord. Le membre clique sur le bouton SentriX, résout le CAPTCHA, puis reçoit le rôle choisi uniquement après réussite.</p></div><span class="sxv9-captcha-badge">CAPTCHA V96 RÉEL</span></div><div class="sxv9-verify-grid"><div class="sxv9-vfield"><label>Salon de vérification</label><select id="sxV9Channel"></select></div><div class="sxv9-vfield"><label>Rôle après réussite</label><select id="sxV9Role"></select></div><div class="sxv9-vfield full"><label>Titre du panneau</label><input id="sxV9Title" maxlength="100" value="Règlement & vérification"></div><div class="sxv9-vfield full"><label>Règlement</label><textarea id="sxV9Rules" maxlength="4000"></textarea></div><div class="sxv9-vfield full"><label>Image HTTPS facultative</label><input id="sxV9Image" type="url" maxlength="500" placeholder="https://…"></div></div><div class="sxv9-verify-options"><label><input id="sxV9Captcha" type="checkbox" checked> CAPTCHA obligatoire</label><label>Tentatives <input id="sxV9Tries" type="number" min="1" max="10" value="3" style="width:58px"></label><label><input id="sxV9Auto" type="checkbox"> Gérer automatiquement l’accès aux salons publics</label></div><div class="sxv9-verify-actions"><button class="btn primary" id="sxV9Publish" type="button">Publier sur Discord</button><button class="btn" id="sxV9VerifyRefresh" type="button">Actualiser</button><div id="sxV9VerifyStatus" class="sxv9-verify-status">Chargement de l’état Discord…</div></div>`;grid.prepend(card);copyOptions(oldChannel,$("sxV9Channel"));copyOptions(oldRole,$("sxV9Role"));$("sxV9Rules").value=oldRules?.value||"";$("sxV9Image").value=oldImage?.value||"";$("sxV9Captcha").checked=oldCaptcha?oldCaptcha.checked:true;$("sxV9Tries").value=oldTries?.value||3;["sxV9Title","sxV9Rules","sxV9Image","sxV9Auto"].forEach(id=>$(id)?.addEventListener("input",e=>e.currentTarget.dataset.touched="1"));$("sxV9Publish")?.addEventListener("click",publishVerify);$("sxV9VerifyRefresh")?.addEventListener("click",loadVerifyState);loadVerifyState()}
function decorate(){const s=S();if(!s)return;const b=document.body,tab=s.tab||"overview";/* n'écrire que si la valeur change : un setAttribute identique déclenche quand même les MutationObserver (V27 relançait l'animation de page toutes les 1,5 s) */if(b.dataset.sxDashboardV9!=="1")b.dataset.sxDashboardV9="1";if(b.dataset.sxTab!==tab)b.dataset.sxTab=tab;ensureHero();mountVerification()}
function start(){decorate();const content=$("content");if(content)new MutationObserver(()=>setTimeout(decorate,0)).observe(content,{childList:true,subtree:true});document.addEventListener("click",e=>{if(e.target?.closest?.("[data-tab]"))setTimeout(decorate,35)},true);setInterval(decorate,1500)}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
})();
</script>
'''


def install(dashboard) -> bool:
    html = str(getattr(dashboard, "INDEX_HTML", "") or "")
    if not html or "</head>" not in html or "</body>" not in html:
        return False
    if 'id="sentrix-unified-adapter-v9-css"' not in html:
        html = html.replace("</head>", V9_CSS + "\n</head>", 1)
    if 'id="sentrix-unified-adapter-v9-js"' not in html:
        html = html.replace("</body>", V9_JS + "\n</body>", 1)
    dashboard.INDEX_HTML = html
    ok = (
        'id="sentrix-unified-adapter-v9-css"' in html
        and 'id="sentrix-unified-adapter-v9-js"' in html
        and 'Vérification Discord réelle' in html
        and 'CAPTCHA V96 RÉEL' in html
        and 'document.getElementById' in html
    )
    logger.warning(
        "Dashboard unified V2 adapter V9 installed=%s: real #content DOM + V96 verification panel.",
        ok,
    )
    return ok


__all__ = ["install", "V9_CSS", "V9_JS"]
